core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^subject/add$', views.subject_add, name='subject_add'),
    url(r'^subject/list$', views.subject_list, name='subject_list'),
]

skart/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from root import views


handler404 = 'error_handlers.views.page_not_found'
handler500 = 'error_handlers.views.server_error'
handler403 = 'error_handlers.views.permission_denied'
handler400 = 'error_handlers.views.bad_request'

urlpatterns = [
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout, {'next_page': "/"}, name='logout'),
    url(r'^change-password/', auth_views.password_change,
        {'template_name': 'registration/change_password.html'}, name='change_password'),
    url(r'^change-password-done/', auth_views.password_change_done,
        {'extra_context': {'some_key': 'some_val'},
         'template_name': 'registration/change_password_done.html'}, name='password_change_done'),
    url(r'^index$', views.index_view, name='index'),
    url(r'^$', views.index_view, name='index'),
    url(r'^core/', include('core.urls')),
    url(r'^refs/', include('refs.urls')),
    url(r'^people/', include('people.urls')),
    url(r'^androlle/', include('androlle.urls')),
    url(r'^location/', include('location.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^learning_process/', include('learning_process.urls')),
    url(r'^documents/', include('documents.urls')),
    url(r'^educational_plan/', include('educational_plan.urls')),
    url(r'^testing/', include('testing.urls')),
    url(r'^statistics/', include('statistics.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testing/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from testing import views


urlpatterns = [
    url(r'^upload/$', views.upload_test,
        name='upload_test'),
    url(r'^show/$', views.show_test_list, name='show_tests'),
    url(r'^download/(?P<test_id>\d+)$', views.download_test, name='download_test'),
    url(r'^test/show/(?P<test_id>\d+)$', views.show_test_internal, name='show_test'),
    url(r'^test/delete/(?P<test_id>\d+)$', views.delete_test, name='delete_test'),
    url(r'^test/variant/(?P<variant_id>\d+)$', views.show_variant, name='show_variant'),
    url(r'^results$', views.show_results, name='test_results'),
    url(r'^test/to_document_test_result/$', views.to_document_test_result, name='to_document_test_result'),
    url(r'^test/standard/append/(?P<test_case>\d+)$', views.append_standard_test, name='append_standard_test'),
    url(r'^test/fitness/append/(?P<test_case>\d+)$', views.append_fitness_test, name='append_fitness_test'),
    url(r'^test/pass/$', views.show_available_test_list, name='show_available_tests'),
    url(r'^test/standard/edit/(?P<question>\d+)$', views.edit_standard_test, name='edit_standard_test'),
    url(r'^test/fitness/edit/(?P<question>\d+)$', views.edit_fitness_test, name='edit_fitness_test'),
    url(r'^test/grant_access/$', views.grant_test_access, name='grant_test_access'),
    url(r'^test/pass/check/(?P<test>\d+)/$', views.pass_test_check, name='pass_test_check'),
    url(r'^test/pass/test/(?P<group_student>\d+)/(?P<question>\d+)/$',
        views.real_pass_test, name='real_pass_test'),
    url(r'^test/result/(?P<group_subject_student>\d+)/$', views.test_result, name='test_result'),

    url(r'^online/test/result/$', views.online_test_result, name='online_test_result'),
    url(r'^online/test/student/errors/$', views.to_document_student_error_doc, name='to_document_student_error_doc'),
    url(r'^online/test/result/download/(?P<group_subject>\d+)/$',
        views.download_test_result, name='download_test_result'),
    url(r'^online/test/student/errors/download/(?P<test_attempt>\d+)/$',
        views.download_student_errors, name='download_student_errors'),
    url(r'^online/test/upload/zip/$', views.unzip_test_images, name='upload_zip_test'),
    url(r'^test/unauthorized/show/$', views.show_unauthorized_tests, name='show_unauthorized_tests'),
    url(r'^test/unauthorized/show/internal/(?P<group_subject_id>\d+)$', views.choose_unauthorized_test,
        name='show_internal_unauthorized_tests'),
    url(r'^test/access/close/$', views.close_tests_access, name="close_tests_access"),
    url(r'^test/change/$', views.change_mark_book_test_case, name="change_test_case"),
]

testing/models.py
# -*- coding: utf-8 -*-

from django.db import models
from core.models import Subject
from django.utils.translation import ugettext_lazy as _
from django.contrib.postgres.fields import HStoreField
from django.contrib.postgres.fields.jsonb import JSONField

from people.models import Teacher, User, Student

STANDARD = u'0'
FITNESS = u'1'
MULTISELECT = u'2'
YES_NO = u'3'
TEST_TYPE = (
    (_('Standard'), STANDARD),
    (_('Fitness'), FITNESS),
    (_('Multiselect'), MULTISELECT),
    (_('Yes/No'), YES_NO)
)


class TestCase(models.Model):
    NEW = 0
    DISABLED = 1
    DELETED = 2
    PROCESSED = 3

    STATE = ((DISABLED, _('Disabled')), (DELETED, _('Deleted')),
             (NEW, _('New')), (PROCESSED, _('Processed')))

    """ Test case is a base class for tests
        Contains questions, fitness questions
        Variants for tests
    """

    subject = models.ForeignKey(Subject, verbose_name=_('Subject'))
    teacher = models.ForeignKey(Teacher, verbose_name=_('Teacher'))
    description = models.CharField(_('Description'), max_length=250)
    code = models.CharField(_('Code'), max_length=80, unique=True)
    state = models.PositiveSmallIntegerField(_('State'), choices=STATE)

    def __unicode__(self):
        return self.code


class Question(models.Model):
    """ Questions """

    ACTIVE = 1
    DISABLED = 2
    DELETED = 3

    STATE = ((ACTIVE, _('Active')), (DISABLED, _('Disabled')), (DELETED, _('Deleted')))

    test_case = models.ForeignKey(TestCase, verbose_name=_("Test case"))
    question = models.TextField(verbose_name=_("Question"))
    test_type = models.CharField((_('Test type')), choices=TEST_TYPE, max_length=10)
    state = models.PositiveSmallIntegerField(_('State'), choices=STATE)

    def __unicode__(self):
        return self.question


class AnswerOption(models.Model):
    """ Answer options for standard questions
        usually there are four options with one correct
    """
    question = models.ForeignKey(Question, verbose_name=_("Question"))
    answer_option = models.TextField(verbose_name=_("Answer option"))
    is_correct = models.BooleanField(_("Is correct"))

    def __unicode__(self):
        return self.answer_option

    class Meta:
        ordering = ['answer_option']


class YesNoQuestion(models.Model):
    NO = 0
    YES = 1
    ANSWER_OPTIONS = ((NO, _('No')), (YES, _('Yes')))

    question = models.ForeignKey(Question, verbose_name=_('Question'))
    correct = models.PositiveSmallIntegerField(choices=ANSWER_OPTIONS)

    def __unicode__(self):
        return u"{} - {}".format(self.question.question, self.get_correct_display())

    class Meta:
        verbose_name = _('Yes no question')
        verbose_name_plural = _('Yes no questions')


class FitnessQuestion(models.Model):
    """ Answer options for fitness questions
        every question contains sub_question
        which have own answer
    """
    question = models.ForeignKey(Question, verbose_name=_('Question'))
    sub_question = models.TextField(_('Sub question'))
    answer = models.TextField(_('Answer'))

    def __unicode__(self):
        return '%s %s' % (self.sub_question, self.answer)


class TestVariantBase(models.Model):
    """ Base class for shuffled variants of tests """

    test_case = models.ForeignKey(TestCase, verbose_name=_('Test case'))
    creator = models.ForeignKey(User, verbose_name=_('Creator'))
    code = models.CharField(_("Code"), max_length=10, db_index=True)
    created_at = models.DateTimeField(_('Created at'), auto_now=True)

    class Meta:
        unique_together = ('test_case', 'code')

    def __unicode__(self):
        return self.code


class TestVariantShuffled(models.Model):
    """
    Shuffled tests

    Test shuffled positions are stored in answers_positions(HStoreField)
    For standard questions
    { 1682 = 4, 1681 = 2, c-pos = 2, 1683 = 1, 1684 = 3 }

    1682, 1681, 1683, 1684 are the answers pk and c-pos is correct answer position
    4, 2, 1, 3 are order of answers
    2 in c-pos means that correct answer for question is positioned in 2 nd place (1681 is correct answer)

    For fitness questions
    { 413_answer-pos = 5, 412_p = 2, 411_answer-pos = 1, 413_p = 3, 414_answer-pos = 4,
             414_p = 4, 415_answer-pos = 3, 411_p = 1, 415_p = 5, 412_answer-pos = 2 }

    413_answer-pos = 5 means that answer for question 413(pk of fitness question) is in position 5
    412_p = 2 means that question 412(pk of fitness question) is positioned in 2 nd place
    """

    test_variant_base = models.ForeignKey(TestVariantBase, verbose_name=_('Test variant'))
    question = models.ForeignKey(Question, verbose_name=_("Question"))
    question_position = models.PositiveSmallIntegerField(_("Question position"))
    answers_positions = HStoreField()


class StudentTestResult(models.Model):
    """ Test results of students """

    student = models.ForeignKey(Student, verbose_name=_('Student'))
    test_variant_base = models.ForeignKey(TestVariantBase, verbose_name=_('Test variant base'))

    # Student chosen answers for questions
    # q1 = 2 means that student selected 2 answer for question 1 (standard questions)
    # fq1 = 2 means that student selected 2 answer for question 1 (fitness questions)
    # { q1 = 2, q2 = 1, q3 = 2, q4=2, q5=1 ... q25 = 3, fq1 = 2, fq2 = 3, fq4 = 5, fq5 = 1 ... fq20 = 3  }
    answers = HStoreField()
    total_score = models.PositiveSmallIntegerField(_('Total score'))


class Attempt:
    FIRST = 0
    SECOND = 1
    THIRD = 2

    ATTEMPTS_COUNT = (
        (FIRST, _('First')),
        (SECOND, _('Second')),
        (THIRD, _('Third'))
    )


class GroupSubject(models.Model):
    NEW = 0
    ACTIVE = 1
    PROCESSING = 2
    FINISHED = 3
    DISABLED = 4
    DELETED = 5

    STATE = ((ACTIVE, _('Active')), (DISABLED, _('Disabled')), (DELETED, _('Deleted')),
             (FINISHED, _('Finished')), (NEW, _('New')), (PROCESSING, _('Processing')))

    test_case = models.ForeignKey(TestCase, verbose_name=_('Test case'))

    standard_question_count = models.IntegerField(_('Standard question count'))
    standard_question_score = models.FloatField(_('Score for standard question'))

    fitness_question_count = models.IntegerField(_('Fitness question count'))
    fitness_question_score = models.FloatField(_('Score for fitness question'))

    yes_no_score = models.FloatField(_('Score for Yes/No question'))
    yes_no_count = models.IntegerField(_('Yes/No question count'))

    multiselect_score = models.FloatField(_('Score for multiselect question'))
    multiselect_count = models.IntegerField(_('Multiselect question count'))

    current_attempt = models.IntegerField(choices=Attempt.ATTEMPTS_COUNT)
    time_limit = models.IntegerField(_('Time limit in minutes'))
    state = models.IntegerField(_('State'), choices=STATE)

    def __unicode__(self):
        return self.test_case.code

    class Meta:
        verbose_name = _('Group and subject')
        verbose_name_plural = _('Group and subjects')


class TestAttempts(models.Model):
    """Attempts for each test """
    PENDING = 0
    STARTED = 1
    FINISHED = 2
    DELETED = 3

    STATE = ((PENDING, _('Pending')), (STARTED, _('Active')),
             (DELETED, _('Deleted')), (FINISHED, _('Finished')))

    group_subject = models.ForeignKey(GroupSubject, verbose_name=_("Group and subject"))
    student = models.ForeignKey(Student, verbose_name=_("Student"))
    test_variant = models.IntegerField(default=1, null=True, blank=True)

    shuffled_questions = JSONField()
    answers = JSONField()

    attempt = models.IntegerField(_('Attempt'), choices=Attempt.ATTEMPTS_COUNT)
    total_score = models.IntegerField(_('Total score'))
    begin_time = models.DateTimeField()
    end_time = models.DateTimeField()
    state = models.IntegerField(_('State'), choices=STATE)

    def __unicode__(self):
        return u"{} - {} - {}".format(self.group_subject.markbook.learning_group,
                                      self.student, self.attempt)

    class Meta:
        unique_together = ('group_subject', 'attempt', 'student')
        verbose_name = "Test attempt"
        verbose_name_plural = "Test attempts"

testing/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _
import autocomplete_light.shortcuts as al
from core.models import Subject
from learning_process.models import LearningGroup
from people.models import Teacher

from .models import TestCase, Attempt

class UploadTestForm(forms.Form):
    # subject = al.ModelChoiceField('SubjectAutocomplete')
    # teacher = al.ModelChoiceField('TeacherAutocomplete')
    code = forms.CharField(max_length=10)
    file = forms.FileField()
    from_docx = forms.BooleanField(required=False)


class ShowTestListForm(forms.Form):
    subject = forms.ModelChoiceField(required=False,
                                     queryset=Subject.objects.all(),
                                     widget=al.ChoiceWidget('SubjectAutocomplete'))
    teacher = forms.ModelChoiceField(required=False,
                                     queryset=Teacher.objects.all(),
                                     widget=al.ChoiceWidget('TeacherAutocomplete'))
    code = forms.ModelChoiceField(required=False,
                                  queryset=TestCase.objects.all(),
                                  widget=al.ChoiceWidget('TestCaseAutocomplete'))
    group = forms.ModelChoiceField(required=False,
                                   queryset=LearningGroup.objects.all(),
                                   widget=al.ChoiceWidget('LearningGroupAutocomplete'))


class ShowResultsListForm(forms.Form):
    test_case = forms.ModelChoiceField(required=False,
                                       queryset=TestCase.objects.all(),
                                       widget=al.ChoiceWidget('TestCaseAutocomplete'))
    group = forms.ModelChoiceField(required=False,
                                   queryset=LearningGroup.objects.all(),
                                   widget=al.ChoiceWidget('LearningGroupAutocomplete'))


class GrantTestAccessForm(forms.Form):
    # subject = forms.ModelChoiceField(queryset=Subject.objects.all(),
    #                                    widget=al.ChoiceWidget('SubjectAutocomplete'))
    #
    group = forms.ModelChoiceField(queryset=LearningGroup.objects.all(),
                                   widget=al.ChoiceWidget('LearningGroupAutocomplete'))

    test_case = forms.ModelChoiceField(queryset=TestCase.objects.all(),
                                       widget=al.ChoiceWidget('TestCaseAutocomplete'))

    time_limit = forms.IntegerField(_('Time limit'))
    
    attempt = forms.ChoiceField(choices=Attempt.ATTEMPTS_COUNT)

    access_granted = forms.BooleanField(required=False)


class TestResultForm(forms.Form):
    group = forms.ModelChoiceField(queryset=LearningGroup.objects.all(),
                                   widget=al.ChoiceWidget('LearningGroupAutocomplete'),
                                   required=False)
    subject = forms.ModelChoiceField(queryset=Subject.objects.all(),
                                     widget=al.ChoiceWidget('SubjectAutocomplete'),
                                     required=False)


class UnzipTestImages(forms.Form):
    """Docstring for UnzipTestImages. """
    file = forms.FileField(required=False)


class UnauthorizedTestAccessForm(forms.Form):
    group = forms.ModelChoiceField(queryset=LearningGroup.objects.all(),
                                   widget=al.ChoiceWidget('LearningGroupAutocomplete'))
    subject = forms.ModelChoiceField(queryset=Subject.objects.all(),
                                           widget=al.ChoiceWidget('SubjectAutocomplete'),
                                           required=False)


class ChangeTestCaseForm(forms.Form):
    old_test_case = forms.ModelChoiceField(queryset=TestCase.objects.all(), 
                                           widget=al.ChoiceWidget('TestCaseForTeacherAutocomplete'))
    new_test_case = forms.ModelChoiceField(queryset=TestCase.objects.all(), 
                                           widget=al.ChoiceWidget('TestCaseForTeacherAutocomplete'))

templates/testing/change_test_case.html
{% extends 'base.html' %}
{% load i18n %}

{% block head %}
    {% include "autocomplete_light/static.html" %}
{% endblock %}

{% block main %}
	<form method="post" onsubmit="return confirm('{% trans "All data of old test case will be erased! Do you really want to continue?" %}');">
	{% csrf_token %}
	<table>
		{{form}}
		<tr>
			<td>
			</td>
			<td><input class='btn btn-primary' type="submit" value="{% trans 'Save' %}"></input></td>
		</tr>
	</table>
	</form>
{% endblock %}

templates/testing/show_results.html
{% extends 'base.html' %}
{% load i18n %}

{% block head %}
    {% include "autocomplete_light/static.html" %}
{% endblock %}

{% block main %}
    <style>
        .correct {
            background: green;
            color: white;
        }
    </style>
    <div class="box-body">
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <input class="btn" type="submit" value="ok">
        </form>
        <table class="table table-bordered" >
            {% for item in data %}
                <tr>
                    <td width="100px">{{ item.test_variant_base.test_case.code }}</td>
                    <td>{{ item.test_variant_base.test_case.subject }}</td>
                    <td>{{ item.student }}</td>
                    <td>{{ item.student.learning_group.get_full_name }}</td>
                    <td>{{ item.total_score }}</td>
                </tr>
            {% endfor %}
        </table>
        <div>
            <a href="{% url 'to_document_test_result' %}" class="btn btn-primary" id = 'doc_export'>{% trans 'Export to word' %} </a>
        </div>
    </div>
    <script>
        window.addEventListener("load",function(){
            var test_case = document.querySelector("#id_test_case").value;
            var group = document.querySelector("#id_group").value;
            var doc_export = document.querySelector("#doc_export");
            if(test_case != "" && test_case != undefined  && group != "" && group != undefined) {
                var href = doc_export.getAttribute("href") + "?group=" + group + "&test_case=" + test_case;
                doc_export.setAttribute("href", href)
            }else{
                doc_export.style.display = 'none';
            }
        },false);

    </script>
{% endblock %}

templates/testing/show_test_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block head %}
    {% include "autocomplete_light/static.html" %}
{% endblock %}

{% block main %}
    <div class="box-header">
    	<h3>{% trans 'Tests' %}</h3>
    	{% if show_filters %}
        <form method="post">
        {% csrf_token %}
            {{ form }}
        <input class='btn btn-primary' type="submit" value="{% trans 'Search' %}">
        </form>
        {% endif %}
    </div>

    <div class="box-body">
    	
    	<div class="pagination" style='width:100%; margin:auto;'>
		    <span class="step-links">
		        {% if data.has_previous %}
		            <a class='btn btn-primary' href="?page={{ data.previous_page_number }}">{% trans 'previous' %}</a>
		        {% endif %}
		
		        <span class="current">
		            {% trans 'Page' %} {{ data.number }} {% trans 'of' %} {{ data.paginator.num_pages }}.
		        </span>
		
		        {% if data.has_next %}
		            <a class='btn btn-primary' href="?page={{ data.next_page_number }}">{% trans 'next' %}</a>
		        {% endif %}
		    </span>
		</div>

        <table class="table">
            {% for d in data %}
                <tr>
					{% if request.user.is_superuser %}
                        <td><a href="{% url 'download_test' test_id=d.group_subject.test_case.pk %}">
                            {% trans 'Download' %}</a></td>
                    {% endif %}
                    <td><a href="{% url 'show_test' test_id=d.group_subject.test_case.pk %}">
                        {% trans 'Show' %}</a></td>
                    <td><a href="{% url 'append_standard_test' test_case=d.group_subject.test_case.pk %}">
                        {% trans 'Add standard test' %}</a></td>
                    <td><a href="{% url 'append_fitness_test' test_case=d.group_subject.test_case.pk %}">
                        {% trans 'Add fitness test' %}</a></td>
                    <td>{{ d.group_subject.test_case.code }}</td>
                    <td>{{ d.subject }}</td>
                    <td>{{ d.learning_group}}</td>
                    <td>{{ d.teacher }}</td>
                    <td>{{ d.group_subject.test_case.question_set.count }}</td>
                    {% if perms.learning_process %}
                       <td><a href="{% url 'delete_test' test_id=d.group_subject.test_case.pk %}">
                           {% trans 'Delete' %}</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/testing/show_variant.html
{% extends 'base.html' %}
{% load i18n %}

{% block head %}
    {% include "autocomplete_light/static.html" %}
{% endblock %}

{% block main %}
    <style>
        .correct {
            background: green;
            color: white;
        }
    </style>
    <div class="box-body">

        <table class="table table-bordered" >
            {% for questions in standard %}
                {% for k, v in questions.items %}
                    <tr><td>{{ forloop.parentloop.counter }}</td><th>{{ k |safe }}</th></tr>
                    {% for answer in v %}
                        <tr><td></td><td>{{ answer |safe }}</td></tr>
                    {% endfor %}
                {% endfor %}
            {% endfor %}
        </table>
        <table class="table table-bordered" >
            {% for questions in fitness %}
                {% for k, v in questions.items %}
                    <tr><td>{{ forloop.parentloop.counter }}</td><th>{{ k |safe }}</th><td></td></tr>
                        {% for q in v %}
                            <tr>
                                <th>{{ forloop.counter }}</th>
                                {% for a in q %}
                                    <td>{{ a |safe}}</td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                {% endfor %}
            {% endfor %}
        </table>
    </div>

    <script>
        var table = document.getElementsByTagName("table");
        var tr = table[1].getElementsByTagName("tr");
        for(i in tr){
            tr[i].onclick = function(){
                var cssClass = "check-selected-question-and-answers";
                var cleanClass = document.getElementsByClassName(cssClass);

                if(cleanClass[0] != undefined){
                    cleanClass[0].setAttribute("class","");
                    cleanClass[0].setAttribute("class","");
                }


                this.getElementsByTagName("td")[0].setAttribute("class",cssClass);
                var questionPos = this.getElementsByTagName("th")[0].innerHTML;
                var answerPos = this.getElementsByTagName("span")[0].innerHTML;
                var pos = answerPos-questionPos;
                var currentPos = parseInt(this.getAttribute("data-pos"));
                if(pos > 0){
                    currentPos = currentPos + Math.abs(pos);
                }else{
                    currentPos = currentPos - Math.abs(pos);
                }

                tr[currentPos].getElementsByTagName("td")[1].setAttribute("class",cssClass);

            }
            tr[i].setAttribute("data-pos",i);
        }
    </script>
    <style>
    .check-selected-question-and-answers{
        background: #F0AD4E;
        color: #ffffff;
    }
    </style>
{% endblock %}

templates/testing/test_internals.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block head %}
    {% include "autocomplete_light/static.html" %}
{% endblock %}

{% block main %}
    <div class="box-body">
        <div class="box-header">
            <table class="table table-bordered">
                <tr>
                    <td>{% trans 'Subject' %}</td>
                    <td>{{ test_case.subject }} </td>
                </tr>
                <tr>
                    <td>{% trans 'Teacher' %}</td>
                    <td>{{ test_case.teacher }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Code' %}</td>
                    <td>{{ test_case.code }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Standard question count' %}</td>
                    <td>{{ standard.count }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Fitness question count' %}</td>
                    <td>{{ fitness.count }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Access status' %}</td>
                {% if standard.count >= 150 and fitness.count >= 50 %}
                    <td class="correct">{% trans 'Access granted' %}</td>
                {% else %}
                    <td class="error">{% trans 'Access denied' %}</td>
                {% endif %}  
                </tr>                
            </table>
        </div>
		<div class='text-center'><h2>{% trans 'Standard questions' %}</h2></div>
        <table class="table">
            {% for question in standard %}
            	<tr>
                    <td class="question" colspan=3>
					    {{ forloop.counter }}. {% trans 'Question' %}:
                        {% if "|||" in question.question %}
                            <img src="/media/{{ question.question|slice:"3:" }}">
                        {% else %}
                            {{ question.question|safe }}
                        {% endif %}
                    </td>

					<td class="question"><a href="{% url 'edit_standard_test' question=question.pk %}">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>
                    </td>
				</tr>
	        	<tr>
				{% for answer in question.answeroption_set.all %}
					{% if answer.is_correct %}
						<td class="correct-answer">
					{% else %}
						<td>
					{% endif %}

                    {% if "|||" in answer.answer_option %}
                        <img src="/media/{{ answer.answer_option|slice:"3:" }}">
                    {% else %}
                         {{ answer.answer_option|safe }}
                    {% endif %}
                </td>
				{% endfor %}
	            </tr>
            {% endfor %}
        </table>
		<div class='text-center'><h2>{% trans 'Fitness questions' %}</h2></div>        
        <table class="table">
            {% for question in fitness %}
            	<tr>
                    <td class="question" colspan=3>
                    	{{ forloop.counter }}. {% trans 'Question' %}:
                        {% if "|||" in question.question %}
                            <img src="/media/{{ question.question|slice:"3:" }}">
                        {% else %}
                            {{ question.question|safe }}
                        {% endif %}
                    </td>
					<td class="question"><a href="{% url 'edit_fitness_test' question=question.pk %}">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>
                    </td>
				</tr>
	
				{% for answer in question.fitnessquestion_set.all %}					
	        		<tr>
                        {% if "|||" in answer.sub_question %}
                            <td colspan="2">
                                <img src="/media/{{ answer.sub_question|slice:"3:" }}">
                            </td>
                        {% else %}
                            <td colspan=2>
                                {{ answer.sub_question |safe }}
                            </td>
                        {% endif %}

                        {% if "|||" in answer.answer %}
                            <td colspan="2">
                                <img src="/media/{{ answer.answer|slice:"3:" }}"></td>
                        {% else %}
                            <td colspan=2>
                                {{ answer.answer |safe }}
                            </td>
                        {% endif %}
		            </tr>
				{% endfor %}
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/testing/upload_test.html
{% extends 'base.html' %}

{% load i18n %}

{% block head %}
    {% include "autocomplete_light/static.html" %}
{% endblock %}

{% block main %}
    <form method="post" enctype="multipart/form-data">
    <table class='table table-bordered'>
    {% csrf_token %}
        {{ form }}
    <tr>
    	<td>
    	</td>
    	<td>
    		<input class='btn btn-primary' type="submit" value="{% trans 'Save'%}">
    	</td>
    </tr>
    
    </table>
    </form>
{% endblock %}